### ISSUE TITLE
Property $application is not set

### ISSUE THREAD

**Issue by MrKey** [Codeception/module-laminas#10]
When trying to access the public property `$application`, it is empty. Also, I could not find where the code sets the property. All I find is that it is only declared in the module class.

What I am trying is this (I use ZF2, but upon inspection it seems that the same applies to Laminas):
```
$this->getModule('ZF2')->application->getServiceManager()
```
But it does not work because of an error.
```

[Error] Call to a member function getServiceManager() on null
```

Is it a bug or there is a specific use case for this property? Could not find any hint in the documentation.

**Comment by Naktibalda** [comment]
Most likely it survived some refactoring where Application object was moved to Connector class.

Are grabServiceFromContainer and addServiceToContainer methods insufficient to your needs?

**Comment by MrKey** [comment]
Of course, it is possible to make workarounds for the legacy stuff I am trying to deal with. Also, from the best practices perspective, the service manager shouldn't be necessary, but the reality is not ideal.

For me it looks like if it was set previously and is not set now after the refactoring, then it could be nice to have it.

https://github.com/Codeception/module-laminas/commit/702b23197f53009bece91c85a248f8a36433b0c0#diff-3e3b04e4a2772338dc7deeff11189beb8f335228293051f7c6f5dfd03c3634d2L85

**Comment by fourhundredfour** [comment]
https://github.com/Codeception/module-laminas/pull/20
