### ISSUE TITLE
Please clarify Doctrine2 compatability status

### ISSUE THREAD

**Issue by bitwombat** [Codeception/module-laminas#5]
Hi - Thanks for this module! 

I see this in the source:

` * Note: services part and Doctrine integration is not compatible with Laminas yet`

Can you please clarify what that means?

**Comment by Naktibalda** [comment]
Actually it was direct translation from `services part and Doctrine integration is not compatible with ZF3 yet`.
And it appears that this issue was fixed by https://github.com/Codeception/Codeception/pull/5566
