### ISSUE TITLE
Deleting incomplete "Codeception for Zend" file

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-laminas#9]
I just opened a PR to remove this file: https://github.com/Codeception/codeception.github.com/pull/478
...but I didn't take a look what's in there ;-) - So you might want to check if there's anything useful and then integrate it into https://codeception.com/docs/modules/Laminas

The ultimate goal is to get rid of the "use cases" dropdown completely, see https://github.com/Codeception/module-symfony/pull/98

**Comment by Naktibalda** [comment]
I read that file - it was a copy of Laravel page and there was nothing specific about Zend Framework, because @DavertMik wasn't familiar with Zend Framework 2.
